version: '3.8'
services:
web:
build: ./backend
command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
- ./backend:/usr/src/app
ports:
- '8000:8000'
env_file:
- .env
depends_on:
- redis
- db


worker:
build: ./backend
command: celery -A worker.celery_app worker --loglevel=info
volumes:
- ./backend:/usr/src/app
env_file:
- .env
depends_on:
- redis
- db


redis:
image: redis:7
ports:
- '6379:6379'


db:
image: postgres:15
environment:
POSTGRES_DB: krishi
POSTGRES_USER: krishi
POSTGRES_PASSWORD: krishi_pass
volumes:
- pgdata:/var/lib/postgresql/data
ports:
- '5432:5432'


volumes:
pgdata: